config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    devise_scope :user do
      get 'users/sign_in', to: 'sessions#new'
      post 'users/sign_in', to: 'sessions#create'
      delete 'users/sign_out', to: 'sessions#destroy'
    end

    resources :dashboard, only: [:index]
    resources :rooms
    resources :users, only: %i[index edit update]

    get :forbidden
  end

  scope :api, module: :api do
    devise_for :users,
               path: '',
               path_names: {
                 sign_in: 'login',
                 sign_out: 'logout',
                 registration: 'signup'
               },
               controllers: {
                 sessions: 'api/users/sessions',
                 registrations: 'api/users/registrations'
               }
    namespace :v1 do
      resources :bookings
      resources :rooms, only: [:index]
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'homepage#index'
  get '/*path' => 'homepage#index'
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :capacity, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/admin/rooms_controller.rb
# frozen_string_literal: true

class Admin::RoomsController < Admin::ApplicationController
  before_action :set_room, only: %i[show edit update destroy]
  before_action :split_tags_param, only: %i[create update]

  def index
    @rooms = Room.order(name: :asc)
  end

  def show; end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)

    if @room.save
      redirect_to admin_room_path(@room), notice: 'Room was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @room.update(room_params)
      redirect_to admin_room_path(@room), notice: 'Room was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @room.destroy
    redirect_to admin_rooms_url, notice: 'Room was successfully deleted.'
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def split_tags_param
    return if params[:room][:tags].blank?

    tags = params[:room][:tags]
    params[:room][:tags] = tags.is_a?(String) ? tags.split(',').map(&:strip) : Array(tags)
  end

  def room_params
    params.require(:room).permit(:name, :capacity, tags: [])
  end
end

app/controllers/api/v1/rooms_controller.rb
# frozen_string_literal: true

class Api::V1::RoomsController < ::Api::ApplicationController
  before_action :authenticate_user!

  def index
    @rooms = Room.all
    room_filter = FilteredRooms.new(@rooms, params)
    @rooms = room_filter.filter_rooms

    render json: @rooms, each_serializer: RoomSerializer
  end
end

app/views/admin/rooms/_form.html.erb
<!-- app/views/rooms/_form.html.erb -->

<%= form_with(model: [:admin, @room], local: true) do |form| %>
  <% if @room.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(@room.errors.count, 'error') %> prohibited this room from being saved:</h2>

      <ul>
        <% @room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :capacity, class: 'form-label' %>
    <%= form.number_field :capacity, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :tags, 'Tags (comma-separated)', class: 'form-label' %>
    <%= form.text_field :tags, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/rooms/edit.html.erb
<div class="row">
  <div class="col-4 offset-4">
    <h1>Edit Room</h1>

    <%= render 'form' %>

    <%= link_to 'Show', admin_room_path(@room), class: 'btn btn-primary' %> |
    <%= link_to 'Back', admin_rooms_path, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/admin/rooms/index.html.erb
<div class="row">
  <div class="col-10 offset-1">
    <h1>Manage Rooms</h1>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Capacity</th>
          <th>Tags</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @rooms.each do |room| %>
          <tr>
            <td><%= room.name %></td>
            <td><%= room.capacity %></td>
            <td><%= room.tags.join(', ') %></td>
            <td><%= link_to 'Show', admin_room_path(room), class: 'btn btn-primary' %></td>
            <td><%= link_to 'Edit', edit_admin_room_path(room), class: 'btn btn-warning' %></td>
            <td><%= link_to 'Destroy', admin_room_path(room), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to 'New Room', new_admin_room_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/admin/rooms/new.html.erb
<div class="row">
  <div class="col-4 offset-4">
    <!-- app/views/rooms/new.html.erb -->

    <h1>New Room</h1>

    <%= render 'form' %>

    <%= link_to 'Back', admin_rooms_path, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/admin/rooms/show.html.erb
<div class="row">
  <div class="col-10 offset-1">
    <p>
      <strong>Name:</strong>
      <%= @room.name %>
    </p>

    <p>
      <strong>Capacity:</strong>
      <%= @room.capacity %>
    </p>

    <p>
      <strong>Tags:</strong>
      <%= @room.tags.join(', ') %>
    </p>

    <%= link_to 'Edit', edit_admin_room_path(@room), class: 'btn btn-warning' %> |
    <%= link_to 'Back', admin_rooms_path, class: 'btn btn-secondary' %>
  </div>
</div>