config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    devise_scope :user do
      get 'users/sign_in', to: 'sessions#new'
      post 'users/sign_in', to: 'sessions#create'
      delete 'users/sign_out', to: 'sessions#destroy'
    end

    resources :dashboard, only: [:index]
    resources :rooms
    resources :users, only: %i[index edit update]

    get :forbidden
  end

  scope :api, module: :api do
    devise_for :users,
               path: '',
               path_names: {
                 sign_in: 'login',
                 sign_out: 'logout',
                 registration: 'signup'
               },
               controllers: {
                 sessions: 'api/users/sessions',
                 registrations: 'api/users/registrations'
               }
    namespace :v1 do
      resources :bookings
      resources :rooms, only: [:index]
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'homepage#index'
  get '/*path' => 'homepage#index'
end

app/views/layouts/admin/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Booking System Admin</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to "Rooms", admin_rooms_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Users", admin_users_path, class: 'nav-link' %>
        </li>
      </ul>
      <div class="d-flex">
        <% if current_user %>
          <%= button_to "Logout", admin_users_sign_out_path, method: :delete, class: 'btn btn-dark' %>
        <% else %>
          <%= button_to "Login", admin_users_sign_in_path, class: 'btn btn-dark' %>
        <% end %>
      </div>
    </div>
  </div>
</nav>