config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    devise_scope :user do
      get 'users/sign_in', to: 'sessions#new'
      post 'users/sign_in', to: 'sessions#create'
      delete 'users/sign_out', to: 'sessions#destroy'
    end

    resources :dashboard, only: [:index]
    resources :rooms
    resources :users, only: %i[index edit update]

    get :forbidden
  end

  scope :api, module: :api do
    devise_for :users,
               path: '',
               path_names: {
                 sign_in: 'login',
                 sign_out: 'logout',
                 registration: 'signup'
               },
               controllers: {
                 sessions: 'api/users/sessions',
                 registrations: 'api/users/registrations'
               }
    namespace :v1 do
      resources :bookings
      resources :rooms, only: [:index]
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'homepage#index'
  get '/*path' => 'homepage#index'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include Devise::JWT::RevocationStrategies::JTIMatcher

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: self

  validates :name, presence: true, uniqueness: true

  has_many :bookings, dependent: :destroy
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < Admin::ApplicationController
  before_action :set_user, only: %i[edit update]

  def index
    @users = User.order(created_at: :desc)
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: 'User was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:admin)
  end
end

app/controllers/api/users/registrations_controller.rb
# frozen_string_literal: true

class Api::Users::RegistrationsController < Devise::RegistrationsController
  protect_from_forgery with: :null_session

  respond_to :json

  private

  def respond_with(current_user, _opts = {})
    if resource.persisted?
      render json: {
        user: UserSerializer.new(current_user).serializable_hash.to_json,
        message: 'Signed up successfully'
      }, status: :ok
    else
      render json: current_user.errors, status: :unprocessable_entity
    end
  end
end

app/controllers/api/users/sessions_controller.rb
# frozen_string_literal: true

class Api::Users::SessionsController < Devise::SessionsController
  protect_from_forgery with: :null_session

  respond_to :json

  private

  def respond_with(current_user, _opts = {})
    if current_user.persisted?
      render json: {
        user: UserSerializer.new(current_user).serializable_hash.to_json,
        message: 'Logged in successfully'
      }, status: :ok
    else
      render json: { message: 'Invalid username/password.' }, status: :unauthorized
    end
  end

  def respond_to_on_destroy
    current_user = User.find(jwt_payload['sub']) if request.headers['Authorization'].present?

    if current_user
      render json: { message: 'Logged out successfully' }, status: :ok
    else
      render json: { message: 'Couldn\'t find an active session.' }, status: :unauthorized
    end
  rescue StandardError => _e
    render json: { message: 'Couldn\'t find an active session.' }, status: :unauthorized
  end

  def jwt_payload
    JWT.decode(
      request.headers['Authorization'].split(' ').last,
      Rails.application.credentials.devise_jwt_secret_key!
    ).first
  end
end

app/views/admin/users/_form.html.erb
<%= form_with(model: user, url: admin_user_path(user)) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row alert alert-secondary">
    <div class="col-sm-10 offset-sm-2">
      <div class="form-check">
        <%= form.check_box :admin, class: 'form-check-input' %>
        <label class="form-check-label" for="user_admin">
          Admin?
        </label>
      </div>
    </div>
  </div>

  <div>
    <%= form.submit 'Update', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/users/_user.html.erb
<tr>
  <td class="text-end">
    <%= link_to "Edit", edit_admin_user_path(user) %>
  </td>
  <td><%= user.id %></td>
  <td><%= "&#x2713;".html_safe if user.admin?  %></td>
  <td><%= user.email %></td>
  <td><%= user.name %></td>
</tr>

app/views/admin/users/edit.html.erb
<div class="row">
  <div class="col-4 offset-4">
    <h1>Edit User: <%= @user.name %></h1>

    <%= render "form", user: @user %>

    <br>

    <div>
      <%= link_to "Back to users", admin_users_path %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="row">
  <div class="col-10 offset-1">
    <p style="color: green"><%= notice %></p>

    <h1>Manage Users</h1>

    <table class="table table-borderd table-hover">
      <thead>
        <tr>
          <th></th>
          <th>ID</th>
          <th>Admin?</th>
          <th>Email</th>
          <th>Name</th>
        </tr>
      </thead>

      <% @users.each do |user| %>
        <%= render user %>
      <% end %>
    </div>

  </div>
</div>